version: '3'
services:
  database:
    # Dockerfile이 있는 위치
#    build: ./database
    image: chouchou8509/docker_test:database
    volumes:
      - ./database/mydb:/var/lib/mysql
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "3306:3306"
  backend:
#    build: ./backend
    image: chouchou8509/docker_test:backend
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    # 환경변수 설정
    environment: 
      - DBHOST=database
  frontend:
#    build: ./frontend
    image: chouchou8509/docker_test:frontend
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "8080:8080"